### ISSUE TITLE
关于登陆页面

### ISSUE THREAD

**Issue by ZigHuang** [nick887/blog-be#1]
我开始尝试自己摸索如何启动项目，但是我在登陆页面遇到了困难
<img width="547" alt="截屏2022-02-22 下午5 59 16" src="https://user-images.githubusercontent.com/75672325/155108604-6d983da9-4d7e-46e5-bc76-6ce3baefa3cd.png">
如图所见，我在`user`表中录入了一些登陆信息，然而在`/login`页面中访问被拒绝了
我想询问后端是否会将密码**加密**存入数据库中,而不是存储的明文🤣

**Comment by Super-ZZGuo** [comment]
> 我开始尝试自己摸索如何启动项目，但是我在登陆页面遇到了困难
> <img alt="截屏2022-02-22 下午5 59 16" width="547" src="https://user-images.githubusercontent.com/75672325/155108604-6d983da9-4d7e-46e5-bc76-6ce3baefa3cd.png">
> 如图所见，我在`user`表中录入了一些登陆信息，然而在`/login`页面中访问被拒绝了
> 我想询问后端是否会将密码**加密**存入数据库中,而不是存储的明文🤣

亦或是有一些其他的细节需要我注意🔍

**Comment by ZigHuang** [comment]
> 我开始尝试自己摸索如何启动项目，但是我在登陆页面遇到了困难
> <img alt="截屏2022-02-22 下午5 59 16" width="547" src="https://user-images.githubusercontent.com/75672325/155108604-6d983da9-4d7e-46e5-bc76-6ce3baefa3cd.png">
> 如图所见，我在`user`表中录入了一些登陆信息，然而在`/login`页面中访问被拒绝了
> 我想询问后端是否会将密码**加密**存入数据库中,而不是存储的明文🤣

蚌埠住了，前端请求地址写错了😮‍💨
