### ISSUE TITLE
关于图片上传功能的实现

### ISSUE THREAD

**Issue by ZigHuang** [nick887/blog-be#2]
我想询问一下博客的`图片/文件上传功能`是如何实现的
后端中似乎没有相对应的接口如`file/upload`,是否需要自己实现**图片/文件存储功能**

**Comment by nick887** [comment]
这个有两个考虑，一个使用对象存储，实现较简单，一个是上传本地存储，本地存储的优势是上传私人资料隐私可以得到保护，一些pdf书籍也不用担心版权问题，本地存储可能需要放到nginx里做，实现麻烦一点，之前因一些事情没有实现，可以自行尝试实现下

**Comment by nick887** [comment]
不好意思理解错了，以为是文件上传，图片功能请参考这篇文章：http://www.nickxiao.icu/blog/3521167082703769587
vscode稍有不同，可以参考插件的官方文档进行配置

**Comment by ZigHuang** [comment]
之前确实只考虑过对象存储和本地存储，`七牛云+图床`的方式还是第一次了解，这就去实践一下（salute🤣
